//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5466
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIExample {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIExample.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created Excel file.
        /// </summary>
        internal static string CreateExcel {
            get {
                return ResourceManager.GetString("CreateExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompress scenario.
        /// </summary>
        internal static string DecompressScenario {
            get {
                return ResourceManager.GetString("DecompressScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\FREEBOX\Disque dur.
        /// </summary>
        internal static string DirectoryDestination {
            get {
                return ResourceManager.GetString("DirectoryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\\Temp.
        /// </summary>
        internal static string DirectoryTmp {
            get {
                return ResourceManager.GetString("DirectoryTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.csv.
        /// </summary>
        internal static string ExcelName {
            get {
                return ResourceManager.GetString("ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export {0}.
        /// </summary>
        internal static string ExportBranch {
            get {
                return ResourceManager.GetString("ExportBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à assets.
        /// </summary>
        internal static string FileNameAssetList {
            get {
                return ResourceManager.GetString("FileNameAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à scenarios.
        /// </summary>
        internal static string FileNameScenarioList {
            get {
                return ResourceManager.GetString("FileNameScenarioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move file to AVEVA.
        /// </summary>
        internal static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\Walkinside\scenarii.
        /// </summary>
        internal static string ScenarioDirectory {
            get {
                return ResourceManager.GetString("ScenarioDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;export peut prendre quelques minutes. Etes-vous sur de vouloir continuer?.
        /// </summary>
        internal static string TextExportAsset {
            get {
                return ResourceManager.GetString("TextExportAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TagName;ProjectName;X;Y;Z;UrlLink.
        /// </summary>
        internal static string TitleColumnExcelAsset {
            get {
                return ResourceManager.GetString("TitleColumnExcelAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TagName;ProjectName;ScenarioName;UrlLink.
        /// </summary>
        internal static string TitleColumnExcelScenario {
            get {
                return ResourceManager.GetString("TitleColumnExcelScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export asset data.
        /// </summary>
        internal static string TitleExportAssetMenu {
            get {
                return ResourceManager.GetString("TitleExportAssetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export scenario.
        /// </summary>
        internal static string TitleExportScenarioMenu {
            get {
                return ResourceManager.GetString("TitleExportScenarioMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://localhost:5050/WVRequest?Project={0}&amp;Scenario={1}.
        /// </summary>
        internal static string UrlLinkScenario {
            get {
                return ResourceManager.GetString("UrlLinkScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://localhost:5050/WVRequest?Project={0}&amp;Tag={1}.
        /// </summary>
        internal static string UrlLinkTag {
            get {
                return ResourceManager.GetString("UrlLinkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\Walkinside\exported models\VRModelECE\.
        /// </summary>
        internal static string VRModelDirectory {
            get {
                return ResourceManager.GetString("VRModelDirectory", resourceCulture);
            }
        }
    }
}
