//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataExporter {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataExporter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TagName;ProjectName;X;Y;Z;UrlRef.
        /// </summary>
        internal static string AssetsFileColumns {
            get {
                return ResourceManager.GetString("AssetsFileColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à assets.
        /// </summary>
        internal static string AssetsListFileName {
            get {
                return ResourceManager.GetString("AssetsListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompress scenario.
        /// </summary>
        internal static string DecompressScenario {
            get {
                return ResourceManager.GetString("DecompressScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;export peut prendre quelques minutes. Etes-vous sûr de vouloir continuer ?.
        /// </summary>
        internal static string EnsureExportAsset {
            get {
                return ResourceManager.GetString("EnsureExportAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.csv.
        /// </summary>
        internal static string ExcelName {
            get {
                return ResourceManager.GetString("ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export {0}.
        /// </summary>
        internal static string ExportBranch {
            get {
                return ResourceManager.GetString("ExportBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel file created.
        /// </summary>
        internal static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moving file to AVEVA.
        /// </summary>
        internal static string FileMovingMessage {
            get {
                return ResourceManager.GetString("FileMovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\[02]_Capgemini\[01]_iALM-R&amp;D\[01]_Innovation\[06]_Walkinside\Dev\Scenarii.
        /// </summary>
        internal static string ScenarioDirectory {
            get {
                return ResourceManager.GetString("ScenarioDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TagName;ProjectName;ScenarioName;UrlRef.
        /// </summary>
        internal static string ScenariosFileColumns {
            get {
                return ResourceManager.GetString("ScenariosFileColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\Temp\Scenarii.
        /// </summary>
        internal static string ScenariosFileTmpDir {
            get {
                return ResourceManager.GetString("ScenariosFileTmpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à scenarios.
        /// </summary>
        internal static string ScenariosListFileName {
            get {
                return ResourceManager.GetString("ScenariosListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export asset data.
        /// </summary>
        internal static string TitleExportAssetMenu {
            get {
                return ResourceManager.GetString("TitleExportAssetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export scenario.
        /// </summary>
        internal static string TitleExportScenarioMenu {
            get {
                return ResourceManager.GetString("TitleExportScenarioMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\Temp.
        /// </summary>
        internal static string TmpDir {
            get {
                return ResourceManager.GetString("TmpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://localhost:5050/WVRequest?Project={0}&amp;Scenario={1}.
        /// </summary>
        internal static string UrlRefScenario {
            get {
                return ResourceManager.GetString("UrlRefScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://localhost:5050/WVRequest?Project={0}&amp;Tag={1}.
        /// </summary>
        internal static string UrlRefTag {
            get {
                return ResourceManager.GetString("UrlRefTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D:\[02]_Capgemini\[01]_iALM-R&amp;D\[01]_Innovation\[06]_Walkinside\Dev\Models\ExportedModels\VRModelECE.
        /// </summary>
        internal static string VRModelDirectory {
            get {
                return ResourceManager.GetString("VRModelDirectory", resourceCulture);
            }
        }
    }
}
